#!/usr/bin/env python
#
# calculatedistance_init.py
#
# Calculate distance between Na+ and Cl- ions, for initial states. When
# calculating the progress coordinate for the initial states, we only care
# about the final timepoint; unlike the case of trajectory segments (i.e.,
# those generated by runseg.sh), we do not need to consider the final timepoint
# of the parent trajectory.
import MDAnalysis
import MDAnalysis.lib.distances

# Load the trajectory.
universe = MDAnalysis.Universe('structure.psf', 'seg.dcd')



for ts in universe.trajectory:
    x1 = universe.select_atoms('bynum 7')
    x2 = universe.select_atoms('bynum 9')
    x3 = universe.select_atoms('bynum 15')
    x4 = universe.select_atoms('bynum 17')
    #calculate position of the atoms
    r1 = x1.positions
    r2 = x2.positions
    r3 = x3.positions
    r4 = x4.positions

    #calculate the dihedral angle
    psi = MDAnalysis.lib.distances.calc_dihedrals(r1,r2,r3,r4)
    psi = psi*(180.0/3.14159)
    psi = psi[0]

    print("{:.2f}".format(psi))


